<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__r1t</name>
   <tag></tag>
   <elementGuidId>491e8a0c-2135-434f-8100-24d7e407328c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-describedby=&quot;\:r1t\:&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-describedby = ':r1t:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;物料主档管理&quot;i] >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>23fb80bb-378b-4976-9f63-067db1b82c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:r1t:</value>
      <webElementGuid>61445910-548b-449b-8639-a72c61c1350f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ClassManagement/EnterpriseProductArchives</value>
      <webElementGuid>acca4a4e-7d54-477f-8d74-2235c78c35c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>物料主档管理</value>
      <webElementGuid>8182ff65-5ce3-4432-8934-2df1f9139f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4bd7b01131dbd4cf8a1e00d0b27db2b1</value>
      <webElementGuid>83785b76-acc9-44e3-b66f-0bcf9bf5e3f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-describedby = ':r1t:']</value>
      <webElementGuid>7845b474-e9fd-4ab3-b826-54fc10b65b1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-describedby = ':r1t:']</value>
      <webElementGuid>d658d617-8219-4742-8f95-4e5cf607e1e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ClassManagement/EnterpriseProductArchives' and (text() = '物料主档管理' or . = '物料主档管理')]</value>
      <webElementGuid>6c4a36fb-c9fd-4425-9dfb-5e442f9f82a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
