<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__r1r</name>
   <tag></tag>
   <elementGuidId>6f65aea7-0c2a-49d6-97db-da3478d70ece</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-describedby = ':r1r:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-describedby=&quot;\:r1r\:&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>96224e1a-12f0-4098-a217-ccd008a42190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:r1r:</value>
      <webElementGuid>c38a820f-ee51-409d-9cc6-415d0bbee42a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ClassManagement/EnterpriseProductArchives</value>
      <webElementGuid>75288073-6274-4690-a962-bd10e8f801ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>物料主档管理</value>
      <webElementGuid>ee5896d7-f323-4587-bb96-3be8c13816ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8866c57262b3f0b297c5f8d92d1d03a5</value>
      <webElementGuid>c7d80ccf-2375-4741-afe8-e8ffb5159de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-describedby = ':r1r:']</value>
      <webElementGuid>c7f197af-d0b8-4d0b-af83-72e332324996</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-describedby = ':r1r:']</value>
      <webElementGuid>3862e35a-c6fb-4f45-b6c7-34e825165bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ClassManagement/EnterpriseProductArchives' and (text() = '物料主档管理' or . = '物料主档管理')]</value>
      <webElementGuid>4669446b-f6ef-4cae-b32c-2875b6da5a25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
