analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3496199,"name"\:"OrangeHRM Trial \#3496199","teamId"\:3490483,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3507112,"accountId"\:null,"sampleProject"\:false,"autoIntegrate"\:false}
analytics.team={"id"\:3490483,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
