<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ant-checkbox-input</name>
   <tag></tag>
   <elementGuidId>eea94a0d-1872-4d92-887b-7160065b3fe9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.ant-table-cell.ant-table-selection-column.ant-table-cell-fix-left.ant-table-cell-row-hover > label.ant-checkbox-wrapper.css-oiqwb9 > span.ant-checkbox.ant-wave-target.css-oiqwb9 > input.ant-checkbox-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;1 SWD-CELL-21700-5000 锂离子蓄电池电芯 归并完成 启用 申请 归类 归并 成品 44139609R9 惠州锂威新能源科技有限公司 - 个 100000116 SFB00001 8507600090 锂离子蓄电池电芯 成品 - 0||用于消费类电子产品电源|正极：三元材料；负极：石墨|260Wh/kg|SUNWODA|21700-5000mAh|5000mAh|不含汞|3.7V (007)个 1 (007)个 1 (035)千克 0.065 - (CNY)人民币 (HKG)中国香港 8507600090 锂离子蓄电池电芯 - 0||用于消费类电子产品电源|正极：三元材料；负极：石墨|260Wh/kg|SUNWODA|21700-5000mAh|5000mAh|不含汞|3.7V (007)个 全流程不涉及美 / 加 (G251111001)SIT测试 2026-04-25 10:56:46 (250723109)测试账号 2026-04-25 11:00:14 - - - 测试 (G251111001)SIT测试 2026-04-25 10:54:12 10 40 13 0 0 9 A 2026-06-15 11:59:05 diff 归并 send 提交备案 close-circle 复审&quot;i] >> internal:label=&quot;&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26c192cf-72b3-4f5f-9c1e-29e134e097b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-checkbox-input</value>
      <webElementGuid>d103863f-d693-4f03-ac86-3ccce461f840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1fc63312-60c3-49f9-b345-9c48866420c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ice-container&quot;)/div[@class=&quot;css-oiqwb9 ant-app&quot;]/div[1]/div[@class=&quot;layout--co76upfi xwd-layout css-oiqwb9 ant-design-pro xwd-layout screen-xl xwd-layout-fix-siderbar xwd-layout-side&quot;]/div[@class=&quot;ant-layout ant-layout-has-sider css-oiqwb9&quot;]/div[@class=&quot;xwd-layout-container css-oiqwb9&quot;]/main[@class=&quot;ant-layout-content xwd-layout-content css-oiqwb9 xwd-layout-has-header css-oiqwb9&quot;]/div[@class=&quot;workspace--ZB0SbHtA&quot;]/div[@class=&quot;pageContent--RS0l6HnF mt-2&quot;]/div[@class=&quot;ka-wrapper&quot;]/div[@class=&quot;ka-content&quot;]/div[@class=&quot;container--dx_3D2cm&quot;]/div[@class=&quot;content--uTjKVrTN&quot;]/section[@class=&quot;sectionBlock--uErZ6WKz listSectionNoHeader--QDP0RdU8&quot;]/div[@class=&quot;pageSectionContent--aBpM98I1 listSectionContent--PyhfRyQI&quot;]/div[@class=&quot;pageStack--r_SsVsHo&quot;]/div[@class=&quot;mainTableScope--KKkJfMpQ&quot;]/div[@class=&quot;space-y-1&quot;]/div[@class=&quot;ant-card ant-card-bordered ant-card-small css-oiqwb9&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-pro-table-shell  ant-pro-table-shell--body-min-height&quot;]/div[@class=&quot;ant-pro-table css-oiqwb9&quot;]/div[@class=&quot;ant-pro-card css-oiqwb9&quot;]/div[@class=&quot;ant-pro-card-body css-oiqwb9&quot;]/div[@class=&quot;ant-table-wrapper css-oiqwb9&quot;]/div[@class=&quot;ant-spin-nested-loading css-oiqwb9&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-table ant-table-small ant-table-bordered css-oiqwb9 ant-table-ping-right ant-table-fixed-column ant-table-scroll-horizontal ant-table-has-fix-left ant-table-has-fix-right&quot;]/div[@class=&quot;ant-table-container&quot;]/div[@class=&quot;ant-table-content&quot;]/table[1]/tbody[@class=&quot;ant-table-tbody&quot;]/tr[@class=&quot;ant-table-row ant-table-row-level-0&quot;]/td[@class=&quot;ant-table-cell ant-table-selection-column ant-table-cell-fix-left ant-table-cell-row-hover&quot;]/label[@class=&quot;ant-checkbox-wrapper css-oiqwb9&quot;]/span[@class=&quot;ant-checkbox ant-wave-target css-oiqwb9&quot;]/input[@class=&quot;ant-checkbox-input&quot;]</value>
      <webElementGuid>118f284e-440b-4de9-834c-7755bb072cfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[3]</value>
      <webElementGuid>2dc20ac7-a1b2-4cb8-8f8e-5fb22e4f602a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ice-container']/div/div/div/div[2]/div[2]/main/div/div[2]/div/div/div/div/section/div[2]/div/div/div/div[2]/div/div/div/div/div/div[2]/div/div/div/div/div/table/tbody/tr[2]/td/label/span/input</value>
      <webElementGuid>3b61a46e-882c-4be4-9df4-c89b9c18d9ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/label/span/input</value>
      <webElementGuid>58d6a3fe-9289-48e3-8ff0-5110d1cdcf61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>ca0ef657-6cea-4cd4-887c-36776648d96c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
