<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_forget_password</name>
   <tag></tag>
   <elementGuidId>ff7cd192-1e05-4e62-91cb-055365a7f1a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ice-container']/div/div/div/div/div[2]/div[2]/form/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;忘记密码&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>efdbe8fc-d668-44f3-9f2b-420be3aa7a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/login/forgot-password</value>
      <webElementGuid>44ea8175-1dc2-49de-bfce-4f24baf1dc95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>忘记密码</value>
      <webElementGuid>13511adf-26d0-4231-8f1d-b1e9768d040a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ice-container&quot;)/div[@class=&quot;css-oiqwb9 ant-app&quot;]/div[@class=&quot;container--RnCwnoSc&quot;]/div[@class=&quot;formWrapper--Qq0D07GV&quot;]/div[@class=&quot;loginForm--Rtwl_Ipb&quot;]/div[@class=&quot;ant-pro-form-login-container css-oiqwb9 css-oiqwb9&quot;]/div[@class=&quot;ant-pro-form-login-main css-oiqwb9&quot;]/form[@class=&quot;ant-form ant-form-vertical ant-form-small css-oiqwb9 ant-pro-form css-oiqwb9&quot;]/div[3]/a[1]</value>
      <webElementGuid>7af61034-64e0-4057-8d3f-1b052373d59e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ice-container']/div/div/div/div/div[2]/div[2]/form/div[3]/a</value>
      <webElementGuid>4c029f17-5d75-4934-abf8-ecf731e0aa69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'忘记密码')]</value>
      <webElementGuid>3204a9cb-8a93-4fce-9840-3a75fbcd0648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='记住密码'])[1]/following::a[1]</value>
      <webElementGuid>d5bbe0eb-103b-44b5-b79b-6c50e76b6765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='请输入密码！'])[1]/following::a[1]</value>
      <webElementGuid>48a3a53f-377d-472a-911a-ac31197e9680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='登 录'])[1]/preceding::a[1]</value>
      <webElementGuid>66150bad-c3f4-40d0-a72d-ce9de3751ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='忘记密码']/parent::*</value>
      <webElementGuid>5530461a-9852-4c46-9416-a2e4ff40e0cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/login/forgot-password')]</value>
      <webElementGuid>458d9128-597e-4e9e-af40-9cb00af826a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>3eab3474-2194-4e48-aeee-bdb57d29fb97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/login/forgot-password' and (text() = '忘记密码' or . = '忘记密码')]</value>
      <webElementGuid>54738b41-1c82-41f3-9cfa-c54573442203</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
