<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__1</name>
   <tag></tag>
   <elementGuidId>dc2e1724-a7aa-41ef-9935-1955dfff748d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'unitCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#unitCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7655fa1-4a3f-462b-8e70-374e9b5fc87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>请输入</value>
      <webElementGuid>9993f411-7457-440f-a3e9-72d1fb8f9029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unitCode</value>
      <webElementGuid>4a0fff09-d15f-428f-8f70-008a5d684216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1d2783f6-4a72-46e8-a715-c7a11a40894c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-sm css-oiqwb9 ant-input-outlined</value>
      <webElementGuid>8d45f3fd-a0b8-4f69-8806-fac7ac3c9f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bf06328b-d5b1-4550-b9cd-473fe7137c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0943827aa2d9f3f622c19864cdca6e55</value>
      <webElementGuid>4a3a4bd5-d56c-4f3c-a963-7e9a76e2a0ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'unitCode']</value>
      <webElementGuid>3b65cd3b-4591-4810-9f4d-ee1a10b64402</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'unitCode']</value>
      <webElementGuid>abdd571d-51bf-49ba-b8c2-905e9c555254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '请输入' and @id = 'unitCode' and @type = 'text']</value>
      <webElementGuid>d9296742-3764-41f2-8f6a-eda6b7211e46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
