<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_files</name>
   <tag></tag>
   <elementGuidId>40f5380e-6d73-4354-9812-958ef63c4b91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'files']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;files&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4916a5b1-031d-42ed-ab3d-c16181a50049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>files</value>
      <webElementGuid>a9d2712e-edd5-49bb-af2f-2547bfd63dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>3e2babdc-dd31-465b-9633-1dcd7205abb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-63d0d3adfe416997ee526ea8a80c118a</value>
      <webElementGuid>d1325a0d-ee58-4492-8fb5-6ac4fca5ec61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'files']</value>
      <webElementGuid>c88580c0-ca73-4d55-9e7e-836f8fa09efb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'files']</value>
      <webElementGuid>31b9834e-09f4-44c7-a337-fcbcc822b0fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'files' and @type = 'file']</value>
      <webElementGuid>33ee2dd9-24d0-4a2d-a5d4-6e94f815e8ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
