<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KG</name>
   <tag></tag>
   <elementGuidId>4f83a7ba-63cf-40c2-b91a-d73d3505ca38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(@id = 'unitWeight') and @class and contains(concat(' ', normalize-space(@class), ' '), ' ant-input-number-input ') and (@role = 'spinbutton')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#unitWeight.ant-input-number-input[role=&quot;spinbutton&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95942c8b-a120-4b32-9d93-9a6ba20d8c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>09c3c352-d2e7-49ca-ae29-5ed13a4e18d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>e450866c-7775-4a53-bac8-ce87a39a3934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5340f55d-5d1c-4976-ba6a-0fbb5448dcab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ee61aec2-a0bb-4f06-a9cf-6a5d8ff74c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unitWeight</value>
      <webElementGuid>71501d43-ea34-4009-8b5b-896f8b24b5e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input-number-input</value>
      <webElementGuid>64c97782-d686-4176-9bd0-d0c84f5ea44a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-56cb78b6200d8df814b08aacee1f67c3</value>
      <webElementGuid>08946480-a3bc-49a6-a5d7-ec3255d50e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@id = 'unitWeight') and @class and contains(concat(' ', normalize-space(@class), ' '), ' ant-input-number-input ') and (@role = 'spinbutton')]</value>
      <webElementGuid>ad3ed3d3-a5f9-49df-b830-efdc9661a8c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@id = 'unitWeight') and @class and contains(concat(' ', normalize-space(@class), ' '), ' ant-input-number-input ') and (@role = 'spinbutton')]</value>
      <webElementGuid>948582e0-2601-45b0-8eb2-79d3e9bf4262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'unitWeight']</value>
      <webElementGuid>423622c4-2ba1-4a34-908d-4acfe9c2d80e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
