<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_</name>
   <tag></tag>
   <elementGuidId>14c0dfce-21f9-491d-a908-13a7a3b9bcdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#itemName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'itemName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b77b57fc-ab08-4cfd-a1ab-5e584ba6da2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>请输入货物名称</value>
      <webElementGuid>46b15fe3-1bf3-44f9-b62c-9aa9d0fc039b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itemName</value>
      <webElementGuid>6925551e-714b-4d17-81ac-b54f0c918729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-sm css-oiqwb9</value>
      <webElementGuid>07ef3ad7-824b-4c27-80db-9b255225936f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d8f0cc6a-2286-4bde-877b-5fe1bfe0c748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e616e1a6f8d11798baffd4c5a0719249</value>
      <webElementGuid>f310c54b-bcb2-484c-aa2f-061bb4776edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'itemName']</value>
      <webElementGuid>916410b1-19b0-47e7-b0bd-ff6e234dcdea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'itemName']</value>
      <webElementGuid>427ed26f-1852-46af-adee-d90c9cb9d466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '请输入货物名称' and @id = 'itemName' and @type = 'text']</value>
      <webElementGuid>89f261b4-9268-4ee6-9d66-046e604217fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
