<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li__r10</name>
   <tag></tag>
   <elementGuidId>58061408-1eab-4a75-a8b7-5652dc9806f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-describedby=&quot;\:r10\:&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '物料归类管理' or . = '物料归类管理')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-describedby = ':r10:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>04a22fe5-bed9-42c4-bff9-ff1549c25674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-menu-overflow-item ant-menu-item ant-menu-item-active ant-menu-item-only-child</value>
      <webElementGuid>de05adf4-b8ff-48bd-8e4a-d3fc9798025c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>0f011034-126f-43c5-98bb-fd17edf5640f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5a5218ea-f0c1-4395-9250-c3e83a907830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:r10:</value>
      <webElementGuid>81703b83-96f6-4b86-8be2-d298006a3909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu-id</name>
      <type>Main</type>
      <value>rc-menu-uuid-73916-2-1996460059972784130</value>
      <webElementGuid>cd1da4b0-c8d3-4b3a-bbff-cb22ab31edc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>物料归类管理</value>
      <webElementGuid>eb566684-c3b8-4cb2-b864-cbabc22d32d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7057238b350185fd2e36f98b6966f07b</value>
      <webElementGuid>80cc7ee8-448a-4bdc-aca7-773e9db6ddea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-describedby = ':r10:']</value>
      <webElementGuid>69b331c3-58a7-4fc6-8985-aa5eab45fb42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-describedby = ':r10:']</value>
      <webElementGuid>92c0d42d-5d0a-4b93-861d-0366957c2c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '物料归类管理' or . = '物料归类管理')]</value>
      <webElementGuid>2ba1a8e1-8e54-46bd-9dc1-07070d962099</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
