<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__4</name>
   <tag></tag>
   <elementGuidId>e43390f5-6ad6-4741-bc4b-28e2a669550f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#itemModel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'itemModel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;企业规格型号&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1359cb47-feb5-400e-a376-35a919969c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>请输入</value>
      <webElementGuid>a874461d-8590-4614-8ecd-a532842ed80f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itemModel</value>
      <webElementGuid>bb69dbe9-b559-4fa5-8c4c-5392d2513265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-sm css-oiqwb9 ant-input-outlined ant-input-status-success</value>
      <webElementGuid>b7d7e372-320e-4d74-ada7-496a98aa0b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>90e869af-1275-4086-b362-9d31ae39b2ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a08e2a000851ad555ece74259bb8f7eb</value>
      <webElementGuid>0992039b-e2d3-4ba8-a81f-f931ee1b5b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'itemModel']</value>
      <webElementGuid>818ae7ef-6244-401e-a73a-2a1855d2aa96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'itemModel']</value>
      <webElementGuid>37f33cd1-2895-4a08-838f-85e3b2d18935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '请输入' and @id = 'itemModel' and @type = 'text']</value>
      <webElementGuid>b20ff266-9290-4769-9213-b07c7d07c393</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
