<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>e8f1ab32-5e15-490b-a03c-62723d819b31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.ant-select-selection-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-selection-item ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form >> internal:has-text=&quot;物料信息料号单位物料类型料件货物名称企业规格型号备注&quot;i >> internal:attr=[title=&quot;料件&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0f95087c-05b3-40a0-9c68-95d1b985bc23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selection-item</value>
      <webElementGuid>d964ee6c-bf87-4d33-a8df-99eafd5ef035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>料件</value>
      <webElementGuid>6f5d6cbd-fe68-4f47-b97e-9d9e6056e4d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>料件</value>
      <webElementGuid>50e13abc-a845-4e31-abdf-55454ca62bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ff2d0c9063c9ad6ac6cc6e6c1fe424e8</value>
      <webElementGuid>816740f5-1e27-419c-97e8-8a81e89c2a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-selection-item ')]</value>
      <webElementGuid>22a6968f-a19a-47bb-8826-37fda06f2f3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-selection-item ')]</value>
      <webElementGuid>1901d921-f61f-4a25-a32d-451463f6333b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = '料件' and (text() = '料件' or . = '料件')]</value>
      <webElementGuid>b72b713f-842e-4581-bb13-3c43d4dbb726</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
