<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_rc-tabs-2-tab-currentFilling</name>
   <tag></tag>
   <elementGuidId>445f06d4-f7a7-4f6b-8e06-4d296f50aa0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-node-key=&quot;currentFilling&quot;] .ant-tabs-tab-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-node-key = 'currentFilling']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-tabs-tab-btn ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;file-done 本次备案/变更&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aa52c004-b045-4e98-ad53-e758059adb9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>727c91d3-745f-4d9e-ad8f-7571dcb3bdf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bc3eb402-35f1-4181-9694-7ec2ea7f7499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-tabs-tab-btn</value>
      <webElementGuid>14183832-a165-4009-aaca-580ee8597e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b0ff418b-bbce-4751-b107-680fa332c088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rc-tabs-2-tab-currentFilling</value>
      <webElementGuid>a678213f-b8ed-4712-a9a0-6a60ff98cc0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>rc-tabs-2-panel-currentFilling</value>
      <webElementGuid>6708b8c5-8f07-4684-95cf-383b4923a2c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>本次备案/变更</value>
      <webElementGuid>a80e1335-ef9a-4d3e-8b73-c9e8ce4ef529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-468bb873fc5d783690e6f710f9df1282</value>
      <webElementGuid>9e009ed2-b1ee-4438-8a86-1ed74ea0265d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-node-key = 'currentFilling']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-tabs-tab-btn ')]</value>
      <webElementGuid>5be61732-fae6-4124-a2f0-c1b48a033347</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-node-key = 'currentFilling']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-tabs-tab-btn ')]</value>
      <webElementGuid>6e70a577-5993-4a52-975d-3c44a156bd94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'rc-tabs-2-tab-currentFilling' and (text() = '本次备案/变更' or . = '本次备案/变更')]</value>
      <webElementGuid>4dedfacb-20a1-41b5-b122-967fcd5368ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
