<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__r1v</name>
   <tag></tag>
   <elementGuidId>b01fdb41-a155-4dcd-94b5-dca843dea596</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-describedby=&quot;\:r1v\:&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-describedby = ':r1v:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;物料归类申请&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cbec86f9-fcd3-4ec7-9809-2c55279a4948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:r1v:</value>
      <webElementGuid>064b5489-77f2-4aa5-b421-1121b7be3beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ClassManagement/GoodsMaintenance</value>
      <webElementGuid>d29a4126-5102-4aef-91f4-a2d3e9f116d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>物料归类申请</value>
      <webElementGuid>5c304ca8-dede-42bf-8b74-5be2ca15099b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-992f712319af1e14b67345c6f8c9b387</value>
      <webElementGuid>71da9bcf-1b5a-407c-a39f-0b010f462439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-describedby = ':r1v:']</value>
      <webElementGuid>82cabb4e-e439-4c83-8fba-0fa791a53972</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-describedby = ':r1v:']</value>
      <webElementGuid>128be0e4-99ef-423b-afa9-10fde6fd1b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ClassManagement/GoodsMaintenance' and (text() = '物料归类申请' or . = '物料归类申请')]</value>
      <webElementGuid>da7b6df1-4cee-4042-afda-edd75c1d9175</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
