<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ag-body-horizontal-scroll-viewport</name>
   <tag></tag>
   <elementGuidId>5f20f514-2fb9-4913-afb5-1180e54da811</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.ag-body-horizontal-scroll-viewport</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ag-body-horizontal-scroll-viewport ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.ag-body-horizontal-scroll-viewport</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>90dc0255-e969-4cb6-9394-48d88920e020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-body-horizontal-scroll-viewport</value>
      <webElementGuid>4cfa30fc-07fb-45b9-9c51-92375ac48349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>eViewport</value>
      <webElementGuid>f6e5a6c1-581e-4539-b289-99279f91a31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-32e0a7e2bdca6d37dd41aff41fb2c521</value>
      <webElementGuid>c6c33fac-a832-4317-9b10-59bc75f93194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ag-body-horizontal-scroll-viewport ')]</value>
      <webElementGuid>e97a3a5b-c51d-4247-a75a-02fdaf0f52ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ag-body-horizontal-scroll-viewport ')]</value>
      <webElementGuid>0cc9202b-7595-4e93-8fb6-bc84d5d316ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
