<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ag-fill-handle</name>
   <tag></tag>
   <elementGuidId>4b257ae1-7ecc-485e-a978-a23313e9b11f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.ag-fill-handle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ag-fill-handle ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;0 无品牌&quot;i] >> div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8cab6a46-ced6-46a0-9947-d23c6f6f7a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-fill-handle</value>
      <webElementGuid>9ece48ae-2cf2-4224-9ab9-81bafe3c20c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9df5e5c3ee41745b23ef2ece048d0e13</value>
      <webElementGuid>bc7ccd41-514b-4289-b314-fbab846f0238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ag-fill-handle ')]</value>
      <webElementGuid>48f4aa03-7967-48d0-b531-6d5b44abe432</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ag-fill-handle ')]</value>
      <webElementGuid>52b8fa10-2cbf-465e-bb45-3b2de56a5ac5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
