<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ag-485-input</name>
   <tag></tag>
   <elementGuidId>2c84ed89-39ec-4c06-84f6-47a29ebab38b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-labelledby=&quot;ag-484-label&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-labelledby = 'ag-484-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;MAT-AUTO-OCJ-001 8507600090&quot;i] >> internal:label=&quot;&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e9794a4-a43d-4867-b817-594af1ae533d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>eInput</value>
      <webElementGuid>ed603e25-15bd-4dfe-9d3b-dafcd30dee74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-input-field-input ag-text-field-input</value>
      <webElementGuid>da8aff89-6baf-421d-9e8c-1e5a3ff95201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>ag-484-label</value>
      <webElementGuid>ba2aed38-d0d4-42e0-95a9-a2bd9930e240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db2d60fc-79e9-488e-8c55-debcc2a8b2fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag-485-input</value>
      <webElementGuid>123cce5f-5cea-4119-9bd2-4e58260009f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>70f4bd10-31de-4568-a61e-a38fded72c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e22b27a6-e5bb-4df0-997f-28f426d404d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>280daa29-5104-4d40-9fd8-042ffba6afbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c3ad63ad-655f-447b-bc07-48ef71d37b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e021631f325116611d5b311bc9d37811</value>
      <webElementGuid>2fbaf83e-feb6-43d4-ae7a-fcaf255cc495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'ag-484-label']</value>
      <webElementGuid>8a1e3f14-3973-4518-b24b-006eedf136ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'ag-484-label']</value>
      <webElementGuid>e7b9abd1-4c98-4384-a87a-7e905fecf525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ag-485-input']</value>
      <webElementGuid>704d7210-6b2d-49a3-87ac-a0cbfd1ec563</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
