<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ag-148-input</name>
   <tag></tag>
   <elementGuidId>35b67a08-b447-40b9-b392-3fe21948e459</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-labelledby=&quot;ag-147-label&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-labelledby = 'ag-147-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;5108050009471 8507600090&quot;i] >> internal:label=&quot;&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>816cb385-1695-4ce7-bc08-8eb5327d8ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>eInput</value>
      <webElementGuid>32e88a27-7898-4505-8d7f-5bfa347f4245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-input-field-input ag-text-field-input</value>
      <webElementGuid>2dbd32b8-ff09-41e3-9f7a-096c4f75aac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>ag-147-label</value>
      <webElementGuid>7a1c8cf3-282c-4006-bdbb-c4ddf24824e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d4d0905d-5641-4d94-aeb5-4a9a2d6013d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag-148-input</value>
      <webElementGuid>eb635530-d7e5-4200-bea0-c5acd82f2a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bd68ecca-ed6a-4c12-b5ec-2030736cd7eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1e5646b9-d038-4db1-82dc-41c2be16d2a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>2a29fb61-cf32-4743-a5c6-0de45e58b14b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>455f90b9-9a35-4614-8e32-2bddf8b0080c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-72bdf61ae5e950239022808b08f61e2e</value>
      <webElementGuid>d377debb-208f-4aa6-b5e6-ccbab9857593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'ag-147-label']</value>
      <webElementGuid>d98e2ae9-66bf-4ecb-a766-a42ed3b3aa9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'ag-147-label']</value>
      <webElementGuid>dd03433b-1b8d-4899-a337-dfdd9aa2d7c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ag-148-input']</value>
      <webElementGuid>c9ed26dd-338f-4386-a677-2f4bf57eef27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
