<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_CHN</name>
   <tag></tag>
   <elementGuidId>9835068b-db73-4dfc-8284-7f5962af3291</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@title = '中国（CHN）']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[title=&quot;中国（CHN）&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;中国（CHN）&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eb70f58d-c687-412b-afc3-0f4933be0102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selection-item</value>
      <webElementGuid>b2bed176-694e-4d52-9aed-c4b7172e2719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>中国（CHN）</value>
      <webElementGuid>ad1da00c-488d-419e-b74b-f52a88ccbab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>中国（CHN）</value>
      <webElementGuid>f2a1310b-24ec-49d7-84af-d23e8886d961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-324edfd69d0f3a709d653481c3a05edb</value>
      <webElementGuid>0c6205cf-89c9-4215-91bb-1f68dca32a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@title = '中国（CHN）']</value>
      <webElementGuid>43f5be37-225d-41bd-9e40-85d406e6967a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@title = '中国（CHN）']</value>
      <webElementGuid>e2974965-a0dc-42ef-b583-11cdb6f323e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = '中国（CHN）' and (text() = '中国（CHN）' or . = '中国（CHN）')]</value>
      <webElementGuid>58444924-cdf1-4fbc-936d-dcd872558251</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
