<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_businessList_list</name>
   <tag></tag>
   <elementGuidId>af7910eb-f860-40c8-9284-aa4bedadf8e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#businessList_list</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'businessList_list']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#businessList_list</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6a0060ae-2086-42b4-8ccf-3cf2a777c744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>ef5ade77-cda4-4e20-a53f-c29a79926638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>businessList_list</value>
      <webElementGuid>c7aaf4ce-f5d0-41aa-a48d-e87c1a049734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item-empty</value>
      <webElementGuid>9179a8cc-0bf5-4ab7-95e2-1fa5063a5c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>暂无数据</value>
      <webElementGuid>9c6ea55c-f8f6-47f3-bb58-09674d77c6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9175e3ff8e6c882a1e1fcd1a5e202c4f</value>
      <webElementGuid>7a3be04d-ecb6-446b-ab1d-798ac758bc43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'businessList_list']</value>
      <webElementGuid>af0c0f2a-8668-45da-94a7-56a37ddc86f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'businessList_list']</value>
      <webElementGuid>c20e1e3d-50ae-4ab5-aff7-63d27f69df66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'businessList_list' and (text() = '暂无数据' or . = '暂无数据')]</value>
      <webElementGuid>4bb41ae5-3524-4635-a8e8-daa723ca2f2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
