<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KG</name>
   <tag></tag>
   <elementGuidId>ba124342-ad72-4276-9d38-7e7ae9dd5c42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unitWeight.ant-input-number-input[role=&quot;spinbutton&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(@id = 'unitWeight') and @class and contains(concat(' ', normalize-space(@class), ' '), ' ant-input-number-input ') and (@role = 'spinbutton')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;单重&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1900bec2-cfb9-4573-b680-90b2c7826ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0722a420-d9d7-4954-816f-68076d021020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>bcc8ee6c-65d2-4d11-b8ea-c82da7c1611c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c121b44c-ae64-4d84-8c64-e31d3c3f00cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>af7ae4d8-5e1d-4f42-8e2a-fa44cfc46f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unitWeight</value>
      <webElementGuid>f77a0bcb-b6c7-4954-95bc-29f5f4d4331e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>06246560-6557-468b-8800-cea0a0426e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input-number-input</value>
      <webElementGuid>f841b290-be9c-446d-a155-af56cb70d641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-56cb78b6200d8df814b08aacee1f67c3</value>
      <webElementGuid>629081d1-f238-4460-b8cc-eb13ce03a007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@id = 'unitWeight') and @class and contains(concat(' ', normalize-space(@class), ' '), ' ant-input-number-input ') and (@role = 'spinbutton')]</value>
      <webElementGuid>653074dc-cbfa-494f-b24e-bfc804f70004</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@id = 'unitWeight') and @class and contains(concat(' ', normalize-space(@class), ' '), ' ant-input-number-input ') and (@role = 'spinbutton')]</value>
      <webElementGuid>a0800cdf-db81-4b01-b45c-be463251ba77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'unitWeight']</value>
      <webElementGuid>2999d639-97a1-400b-b8c3-99fbab7968ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
