<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_rc_select_35_1</name>
   <tag></tag>
   <elementGuidId>6d689659-caf9-4dcd-b46f-2cf5062f89dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.required-field.ant-select-sm .ant-select-selection-search-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' required-field ') and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-sm ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-selection-search-input ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#rc_select_35</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>101eab7d-bdb7-4298-bfce-fb40d81f9855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>4315c380-83b8-4555-ae70-682c081ea3bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>48e3e484-c9fc-4c85-8639-435a7ada579f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selection-search-input</value>
      <webElementGuid>8d979b5f-380e-4f72-83e9-825519d2a592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>76bd8497-02d1-4aef-9868-0c13b95684c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>48d6f153-d2ad-4037-b94b-e94165deba1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>2862007c-02fe-4e33-8560-8b584a874f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>rc_select_35_list</value>
      <webElementGuid>f68fafda-78b5-4479-ad67-50d05327fc03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>8959813f-7e21-4ce2-aafe-40852cc1ffa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>rc_select_35_list</value>
      <webElementGuid>a2d5a2a3-ab68-4058-8f2e-36fe325566cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3b534bc7-9261-4355-8b29-282650de836b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rc_select_35</value>
      <webElementGuid>aa7ffc6d-1acb-4d4f-a932-d337284ae88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>rc_select_35_list_0</value>
      <webElementGuid>5f602273-b9bc-465c-979a-208c3acd13a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-6b3fbc6139b7fd308ad75fa47c3de76a</value>
      <webElementGuid>bd22fe5a-5582-4a97-accb-c7df6e37f7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' required-field ') and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-sm ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-selection-search-input ')]</value>
      <webElementGuid>adb9fd8d-ce36-4971-96b3-3eb42a20f561</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' required-field ') and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-sm ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-selection-search-input ')]</value>
      <webElementGuid>aa40ff65-674a-4182-b1ca-a585b7805bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'rc_select_35']</value>
      <webElementGuid>ffb1f866-7a5b-47ae-93a1-50f63a52f210</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
