<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_rc_select_35</name>
   <tag></tag>
   <elementGuidId>ff7f9acf-c2a2-4c2d-ae33-b20726ff483c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.required-field.ant-select-sm .ant-select-selection-search-input[aria-autocomplete=&quot;list&quot;][role=&quot;combobox&quot;][type=&quot;search&quot;][aria-haspopup=&quot;listbox&quot;][autocomplete=&quot;off&quot;][value=&quot;&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' required-field ') and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-sm ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-selection-search-input ') and (@aria-autocomplete = 'list') and (@role = 'combobox') and (@type = 'search') and (@aria-haspopup = 'listbox') and (@autocomplete = 'off') and (@value = '')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#rc_select_35</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c1edd7e-3409-4f68-b608-429246ba4135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>14c0a627-1b3b-4435-b8ee-302dba32aefc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e001ea1c-5ab4-41b1-8667-3508a1cfafd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selection-search-input</value>
      <webElementGuid>8d12bd90-74ca-48d2-af64-da219ba7a020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>287aabb4-a916-47bc-95e4-adaf4ebc1898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bcaf82c7-dfc5-4681-bb7c-fa9250d812a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>9f2db0f7-fa49-4b1c-ae04-f4ae90495951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>rc_select_35_list</value>
      <webElementGuid>9986ba36-3a82-46a3-995e-8b8d166c0ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>cc34ffb9-53fb-4550-877a-a6107968cc69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>rc_select_35_list</value>
      <webElementGuid>775a82e2-457a-4b50-a4cf-9805a1d420eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rc_select_35</value>
      <webElementGuid>261da6d2-5c65-46a4-b089-e5071058569a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>rc_select_35_list_0</value>
      <webElementGuid>f0674258-596d-45a4-8482-9efce90892fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-66df7ff4847b26407c325cdf0c40ec0d</value>
      <webElementGuid>e0e899bc-c100-45aa-a926-085055dc1bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' required-field ') and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-sm ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-selection-search-input ') and (@aria-autocomplete = 'list') and (@role = 'combobox') and (@type = 'search') and (@aria-haspopup = 'listbox') and (@autocomplete = 'off') and (@value = '')]</value>
      <webElementGuid>12df8107-d736-4be7-8cf4-34a1a77c1c4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' required-field ') and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-sm ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-selection-search-input ') and (@aria-autocomplete = 'list') and (@role = 'combobox') and (@type = 'search') and (@aria-haspopup = 'listbox') and (@autocomplete = 'off') and (@value = '')]</value>
      <webElementGuid>2c6f0ee7-c3d2-4f43-8769-a03636526c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'rc_select_35']</value>
      <webElementGuid>267eb003-9447-4963-9532-25253622023e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
