<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_(CHN)</name>
   <tag></tag>
   <elementGuidId>901f116b-e0b9-46ab-9ef8-2eadab065b37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.truncate[title=&quot;\(CHN\)中国&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' truncate ') and (@title = '(CHN)中国')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;(CHN)中国&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2d6ec06b-b28e-478f-bec6-735808a275b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-1 text-left truncate</value>
      <webElementGuid>fa9338b3-80a4-461c-af06-0fa3e6d8dfdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>(CHN)中国</value>
      <webElementGuid>e24c0198-c090-496f-91be-227190fde4e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(CHN)中国</value>
      <webElementGuid>5a804183-9635-42f2-99d6-397af4c4290c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e5146ba439f22bf99ab76a53c1ca7e35</value>
      <webElementGuid>6466a022-bc08-4c3f-988a-d8ba2c8af157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' truncate ') and (@title = '(CHN)中国')]</value>
      <webElementGuid>052be811-e32b-4bfe-82c5-cfd647f4330c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' truncate ') and (@title = '(CHN)中国')]</value>
      <webElementGuid>5869a77c-11b6-4323-adf8-d46bca742152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = '(CHN)中国' and (text() = '(CHN)中国' or . = '(CHN)中国')]</value>
      <webElementGuid>b1c75163-4a53-4228-b92b-a9700d554c7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
