<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__r1t</name>
   <tag></tag>
   <elementGuidId>45750bb1-dfc1-40cb-bdd7-a1f47ed5a67d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-describedby=&quot;\:r1t\:&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-describedby = ':r1t:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;物料归类申请&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>43d08998-471f-429a-886f-61711aa6ae20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:r1t:</value>
      <webElementGuid>002e02b9-8410-471d-8dc8-899e7e13660d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ClassManagement/goodsMaintenance</value>
      <webElementGuid>60249d38-b185-4c50-a6ba-4237d55305fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>物料归类申请</value>
      <webElementGuid>0740e60a-bf5c-4936-be34-ce219a459270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4bd7b01131dbd4cf8a1e00d0b27db2b1</value>
      <webElementGuid>19a080ef-cbc7-4434-a15d-546775d02bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-describedby = ':r1t:']</value>
      <webElementGuid>faacb486-706f-4a73-8021-3afb72b3cc1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-describedby = ':r1t:']</value>
      <webElementGuid>0e75ea63-5180-4d6c-add3-49e4fa85d30f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ClassManagement/goodsMaintenance' and (text() = '物料归类申请' or . = '物料归类申请')]</value>
      <webElementGuid>9a0c0cc4-94c5-4536-ace3-05ee8a6a5026</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
