<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_</name>
   <tag></tag>
   <elementGuidId>c41d59ff-a225-4a62-8420-1af37a03032b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#itemName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'itemName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;请输入货物名称&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec9ee6c8-3258-48cc-bd11-358ace8ee7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>请输入货物名称</value>
      <webElementGuid>9137c0e9-eba5-4da0-9add-702b63c85234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itemName</value>
      <webElementGuid>a7eea765-c800-4af5-98a6-a7c935ffaf51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-sm css-oiqwb9</value>
      <webElementGuid>08483eb9-a985-433c-ad5e-ffbd1c6591d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>18086315-9583-4820-b22c-5b2819ebab6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e616e1a6f8d11798baffd4c5a0719249</value>
      <webElementGuid>75c9c511-7e84-4c29-a2bb-1de555522c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'itemName']</value>
      <webElementGuid>154e7f08-d1ea-4454-a559-cf4d0a34731e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'itemName']</value>
      <webElementGuid>60a5dd68-a809-4e65-bacf-e3e0358b2c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '请输入货物名称' and @id = 'itemName' and @type = 'text']</value>
      <webElementGuid>92d30f20-d5c9-4ce0-9292-498ca31e6d78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
