<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__4</name>
   <tag></tag>
   <elementGuidId>36ad54c4-a59b-4036-887b-6b1e93e10e24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#itemModel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'itemModel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;企业规格型号&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9527bd17-e1bf-41ad-8f6d-adbc6fb3628f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>请输入</value>
      <webElementGuid>40047972-b699-49de-9b36-49481c5ac247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itemModel</value>
      <webElementGuid>5efd0f92-1634-4d69-a9f0-f41627bf1884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-sm css-oiqwb9 ant-input-outlined</value>
      <webElementGuid>4d7567c2-78bc-460d-a70a-688a7204aab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>17502ede-985d-4e57-a2a3-32432092097d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a08e2a000851ad555ece74259bb8f7eb</value>
      <webElementGuid>34a9625e-c412-40f7-bc40-7b0788d0d9f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'itemModel']</value>
      <webElementGuid>53555950-6b20-4d39-b0da-488900050c04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'itemModel']</value>
      <webElementGuid>47a746ce-9785-46dc-b24b-2ef3abf339f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '请输入' and @id = 'itemModel' and @type = 'text']</value>
      <webElementGuid>06dfe2ea-7411-424f-b378-13bd69f27321</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
