<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__7</name>
   <tag></tag>
   <elementGuidId>5da5c5c3-8341-4088-be3b-981bdea334d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ouName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'ouName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;请输入事业部名称&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>359fe780-ef27-4101-a11e-5d3a8385baae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>请输入事业部名称</value>
      <webElementGuid>8d64ba41-b2df-489f-b570-6b906ece3d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ouName</value>
      <webElementGuid>27357f33-ffe9-4ec2-aec8-fe9d23ed491d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-sm css-oiqwb9</value>
      <webElementGuid>30ab8a39-f7c7-4056-bd35-46f9c6be0b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c5c46d78-870b-4ca0-80a3-9aaf07f5ac63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d0970c73d54a588ca96244bb5ead623d</value>
      <webElementGuid>6037b2f2-010b-4aa0-b417-51fabcde2df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'ouName']</value>
      <webElementGuid>6c8b76fc-ca5f-4cae-8fc3-6d4134bd6a6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'ouName']</value>
      <webElementGuid>422d293c-a9ff-48bb-aad6-4d2eb11693d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '请输入事业部名称' and @id = 'ouName' and @type = 'text']</value>
      <webElementGuid>5733ba89-05ce-4647-8126-c447401de8fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
