<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_oriCountry_list</name>
   <tag></tag>
   <elementGuidId>8b7aad65-48a7-497b-a677-89af0eec0f27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'oriCountry_list']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#oriCountry_list</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#oriCountry_list</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0d9af7c7-1552-4628-83f2-c1e53f666b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>ec12e527-706c-4f33-bbef-41d4e6388630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oriCountry_list</value>
      <webElementGuid>08a531f0-4951-4944-a443-47c8485a501e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item-empty</value>
      <webElementGuid>11378ec6-0893-4f0f-bfce-cb0c661d4f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>暂无数据</value>
      <webElementGuid>ea7efa3f-cb42-449a-bc69-6200604dc3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-605846760c2fb977ec159fc147aa3165</value>
      <webElementGuid>a9987506-cbf5-4935-8b1b-6819258d6a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'oriCountry_list']</value>
      <webElementGuid>75c70a94-d9eb-41ca-8195-304010ae5ddf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'oriCountry_list']</value>
      <webElementGuid>b3a21b5a-c952-40df-8535-4f3026d7fd6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'oriCountry_list' and (text() = '暂无数据' or . = '暂无数据')]</value>
      <webElementGuid>d02c9ccf-c886-4268-a6a4-8d71d08063d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
