<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_compCode_list</name>
   <tag></tag>
   <elementGuidId>63e2cc84-b1e3-44ca-ad6b-92074a2980d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'compCode_list']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#compCode_list</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;暂无数据&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>83fe7936-ba7f-484b-89be-a6ba19e7f43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>3aff47b0-af8e-43ec-aa25-f2889c71b01b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>compCode_list</value>
      <webElementGuid>46f9fe4e-5b59-47f8-97e9-0b2c1911ebb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item-empty</value>
      <webElementGuid>6f98e827-c98d-46dd-80d0-87ebb53ab1ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>暂无数据</value>
      <webElementGuid>3b336d00-092b-4a09-a8bc-61340028cf44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2a43bee2c4753a647d83ccb20eae7ac0</value>
      <webElementGuid>03a3ece9-1f0c-444b-a420-3f72743586db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'compCode_list']</value>
      <webElementGuid>68692798-aa8d-4a7d-a289-559eb7a17d3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'compCode_list']</value>
      <webElementGuid>472f9608-9b1c-4ea8-8e01-a9a5bc475ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'compCode_list' and (text() = '暂无数据' or . = '暂无数据')]</value>
      <webElementGuid>a6f076c9-110a-40e5-8ce4-411441ccf660</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
