<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__1</name>
   <tag></tag>
   <elementGuidId>9dfcf683-50ef-4ab9-869e-9bcc7aa183a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'itemCodes']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#itemCodes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;请输入物料料号，多个料号可换行&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3c0fffe6-45a9-49e8-883b-842aa538a19f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>请输入物料料号，多个料号可换行</value>
      <webElementGuid>7916be90-f0c8-4ff6-a7e8-0ec12ffb1d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ed00aad6-1ae3-4633-9917-a849fc266930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itemCodes</value>
      <webElementGuid>bbf7b74f-577a-49a6-9325-dd2e5e30987e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-sm css-oiqwb9 advanced-filter-textarea-control</value>
      <webElementGuid>364d824c-7177-4b42-a8a6-aa288e71a966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1234f70e7e48680523a8c9c5ec358fdb</value>
      <webElementGuid>ef06f4f8-0eaa-4f90-8033-e5a094d95e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'itemCodes']</value>
      <webElementGuid>9519c6d7-19c6-4816-b928-503976660749</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'itemCodes']</value>
      <webElementGuid>8e28c5a1-7bb8-473a-8bdd-dbc532aac56b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = '请输入物料料号，多个料号可换行' and @id = 'itemCodes']</value>
      <webElementGuid>c15361a7-7101-45a2-8a00-5cfe7b9a8070</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
