<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_101</name>
   <tag></tag>
   <elementGuidId>7cb20084-a61e-4cff-9b48-cc5708f7ae8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[title=&quot;保税进出&quot;] .whitespace-nowrap.w-max</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@title = '保税进出']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' whitespace-nowrap ') and contains(concat(' ', normalize-space(@class), ' '), ' w-max ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;101保税进出&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d0f61121-ac3a-4d28-bf55-aac1934b5224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex w-max min-w-full items-center gap-1 whitespace-nowrap pr-2</value>
      <webElementGuid>f7aae290-4e0c-440f-a01b-1782b7ba07cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>101 保税进出</value>
      <webElementGuid>cf82b1b4-a0a9-4c94-a946-906577d3ae7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>101保税进出</value>
      <webElementGuid>f9bcccf0-46e3-4478-a827-372d656b9ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8c7264ec5ce8ee588b2195b62588f086</value>
      <webElementGuid>5e061f7d-fe5e-49ca-be26-b2d283c96a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@title = '保税进出']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' whitespace-nowrap ') and contains(concat(' ', normalize-space(@class), ' '), ' w-max ')]</value>
      <webElementGuid>608fd713-07e1-4581-9b45-e0e7fb37db23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@title = '保税进出']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' whitespace-nowrap ') and contains(concat(' ', normalize-space(@class), ' '), ' w-max ')]</value>
      <webElementGuid>42936610-5c61-4f5e-850c-beca67769ed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = '101 保税进出' and (text() = '101保税进出' or . = '101保税进出')]</value>
      <webElementGuid>c3a46500-f7ab-4597-af31-8cf70cd93181</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
