<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_rc-tabs-2-tab-price</name>
   <tag></tag>
   <elementGuidId>700e2470-c4c1-4da2-a519-8aa0c4547d0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-node-key=&quot;price&quot;] .ant-tabs-tab-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-node-key = 'price']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-tabs-tab-btn ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;定价信息&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ea53c31d-dde7-45ab-8598-0396305702d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>e5e2a078-dfde-47ed-8940-7cecf3cee41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ce6df6d7-58ff-408e-86ea-19d1fc2a1423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-tabs-tab-btn</value>
      <webElementGuid>107db5cf-01ff-4afe-b977-5d70eceb405b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5a6b62cb-3b49-436e-a909-d92b88f8b9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rc-tabs-2-tab-price</value>
      <webElementGuid>496a0b42-c7b3-491a-bb51-c66b5d11fbda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>rc-tabs-2-panel-price</value>
      <webElementGuid>63eef8af-71f7-49b4-b529-5362bac84973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>定价信息</value>
      <webElementGuid>235642eb-f654-4f8b-8841-ccdd1752d8b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9331d3aa5580f727f0478d9af81dc09e</value>
      <webElementGuid>a47a8a6f-3d25-4299-94a0-eee179275e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-node-key = 'price']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-tabs-tab-btn ')]</value>
      <webElementGuid>e8b28dce-c7a7-46de-ae9d-fee3b5841a22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-node-key = 'price']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-tabs-tab-btn ')]</value>
      <webElementGuid>1e5260bc-b741-4864-bf58-5aff4e39c7f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'rc-tabs-2-tab-price' and (text() = '定价信息' or . = '定价信息')]</value>
      <webElementGuid>fca0660f-0905-4e17-bd78-c25180bb8afc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
