<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__3</name>
   <tag></tag>
   <elementGuidId>cc89e565-3a97-4589-8558-b7de319a36f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#changeReason.ant-input-sm.ant-input-outlined.ant-input-status-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='itemCode']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'changeReason' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;货物名称&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da494de5-900c-4c13-a866-4f896b2dc846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>请输入</value>
      <webElementGuid>f1c1956e-a859-44a6-9f8b-ef0661f05b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>changeReason</value>
      <webElementGuid>3b2d96e2-f3cd-4b61-8026-46eb60f606d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dc6d723b-443b-4878-afb3-c3e43aabde93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-sm css-oiqwb9 ant-input-outlined ant-input-status-success</value>
      <webElementGuid>7e0042d5-165a-425c-9299-213817b59250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>abf07037-9344-4ff8-8138-5cb75f51b008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7c17618a6ef5e90ebdb95340401ce2c7</value>
      <webElementGuid>44899ff4-1e5e-4b0a-9d31-b19bd2527b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@id = 'changeReason') and @class and contains(concat(' ', normalize-space(@class), ' '), ' ant-input-sm ') and contains(concat(' ', normalize-space(@class), ' '), ' ant-input-outlined ') and contains(concat(' ', normalize-space(@class), ' '), ' ant-input-status-success ')]</value>
      <webElementGuid>cfd3b479-0fc5-4b19-8d65-314ab6882521</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@id = 'changeReason') and @class and contains(concat(' ', normalize-space(@class), ' '), ' ant-input-sm ') and contains(concat(' ', normalize-space(@class), ' '), ' ant-input-outlined ') and contains(concat(' ', normalize-space(@class), ' '), ' ant-input-status-success ')]</value>
      <webElementGuid>43ebd057-8b11-4c74-b437-e6d75ca93ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'changeReason' and @type = 'text']</value>
      <webElementGuid>8785a216-0c50-434e-814a-3698615e2edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'itemName']</value>
      <webElementGuid>df8e3af7-9842-47eb-983e-3710e230aa47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '请输入' and @id = 'itemName' and @type = 'text']</value>
      <webElementGuid>412b9b58-bcc1-478e-b99d-b981ad6fab96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
