<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__6</name>
   <tag></tag>
   <elementGuidId>05b7f9cd-1e33-4e2b-af6d-3c4e025e7205</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ouCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unitCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;请输入事业部编码&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe292a8f-43d3-4436-8328-4dc1ebc4ba66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>请输入事业部编码</value>
      <webElementGuid>3d46e4e6-2ba7-4c13-9fda-bab85ceee074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ouCode</value>
      <webElementGuid>2a93b65c-37f1-41d8-9746-542ef8d30adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-sm css-oiqwb9</value>
      <webElementGuid>0555e95f-a4a0-44a3-accb-8c9fabb99637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5fc2af75-067f-4eed-aba7-57afe3b5b78c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-908f7b4b73c660040ac5022214a1fb66</value>
      <webElementGuid>7283e180-a958-4f61-b644-2bbca3b02f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'ouCode']</value>
      <webElementGuid>0d56b8e2-ea3b-4e0e-90d2-54292601807c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'ouCode']</value>
      <webElementGuid>591b155d-1891-4ccb-b987-7a06369a988c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '请输入事业部编码' and @id = 'ouCode' and @type = 'text']</value>
      <webElementGuid>2ff68e7f-3b28-49f6-aebf-2f701717e155</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
