<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_rc_select_34</name>
   <tag></tag>
   <elementGuidId>af8a9206-0792-4d03-9376-73f7f229e5fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.required-field.ant-select-sm .ant-select-selection-search-input[aria-autocomplete=&quot;list&quot;][role=&quot;combobox&quot;][type=&quot;search&quot;][aria-haspopup=&quot;listbox&quot;][autocomplete=&quot;off&quot;][value=&quot;&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' required-field ') and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-sm ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-selection-search-input ') and (@aria-autocomplete = 'list') and (@role = 'combobox') and (@type = 'search') and (@aria-haspopup = 'listbox') and (@autocomplete = 'off') and (@value = '')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3012f89e-9bd5-4199-b3dc-833920b9b562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>480f493a-e359-4247-8621-0d076aed1114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>33e35254-3cd1-4429-916a-75e9f47532ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selection-search-input</value>
      <webElementGuid>0bb860af-97f0-4ca5-9526-01e6624fe3cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>00470419-72b8-43f5-a0ba-f6c0f8b24cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e8171575-613c-45f1-8d22-52e95b10cf00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>de20aa99-2e99-4921-9682-5c364c6a0eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>rc_select_34_list</value>
      <webElementGuid>b5c6f07c-31d9-49be-81c2-03d4deba37a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>ea0c139f-e2b4-4afc-a3fd-da02a461ab2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>rc_select_34_list</value>
      <webElementGuid>1927d2f9-02b7-4a25-90ce-0f7df32205fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rc_select_34</value>
      <webElementGuid>71650e82-9268-4d39-b863-426f33dc1ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>rc_select_34_list_0</value>
      <webElementGuid>e7d1d766-820d-40bb-97a3-0f0423ce6db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-66df7ff4847b26407c325cdf0c40ec0d</value>
      <webElementGuid>1f0b4992-03b3-49f1-b323-8c1f3bb989df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' required-field ') and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-sm ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-selection-search-input ') and (@aria-autocomplete = 'list') and (@role = 'combobox') and (@type = 'search') and (@aria-haspopup = 'listbox') and (@autocomplete = 'off') and (@value = '')]</value>
      <webElementGuid>a4aed992-660c-495e-9cac-f4c834909465</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' required-field ') and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-sm ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-selection-search-input ') and (@aria-autocomplete = 'list') and (@role = 'combobox') and (@type = 'search') and (@aria-haspopup = 'listbox') and (@autocomplete = 'off') and (@value = '')]</value>
      <webElementGuid>43e4a299-055a-4560-b0fe-03a74d57bf99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'rc_select_34']</value>
      <webElementGuid>6a95d9a2-f980-459b-9e88-737dd238b0ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
