<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_(USD)</name>
   <tag></tag>
   <elementGuidId>ead9f831-6868-4946-8186-2e822c3b8c11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.truncate[title=&quot;\(USD\)美元&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' truncate ') and (@title = '(USD)美元')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;(USD)美元&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7f32e66c-fdb8-4c94-b36d-38e116c705f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-1 text-left truncate</value>
      <webElementGuid>310238a4-702f-47d2-84ef-d87148e41bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>(USD)美元</value>
      <webElementGuid>cf5f5ec3-d5db-484a-92dd-9079f9a2ce01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(USD)美元</value>
      <webElementGuid>e8e94c7c-550e-4b18-88eb-0d80d94f71c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-bc33ed8b4191386023d387f3dbbb66c5</value>
      <webElementGuid>cad5dc55-c03b-43b9-b6b4-661646228913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' truncate ') and (@title = '(USD)美元')]</value>
      <webElementGuid>6055c7ce-bfc4-4eb4-8d4a-9d3a12e9ba07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' truncate ') and (@title = '(USD)美元')]</value>
      <webElementGuid>25434c94-93eb-4869-af0c-79f631fbc22b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = '(USD)美元' and (text() = '(USD)美元' or . = '(USD)美元')]</value>
      <webElementGuid>49ae0214-1029-4b27-8234-5e158d24a9d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
