<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__4</name>
   <tag></tag>
   <elementGuidId>895a8a0d-f6fb-4ff7-b38e-13734f6f2479</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[title=&quot;客户&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@title = '客户']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;客户&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b4cf3391-fd3f-479b-aaa4-99da9820b3b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selection-item</value>
      <webElementGuid>c8b265e8-7093-47f7-84d2-e9f4a298b0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>客户</value>
      <webElementGuid>37e4a25f-2106-40a3-b5d6-fa8c814ce1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>客户</value>
      <webElementGuid>215f0125-f1a0-4a3e-bf4f-6fbdcb506f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3b2bcaab1f4c56dd1c27690c7caee213</value>
      <webElementGuid>ddb5aa3c-d10c-4c41-9394-b946121da4d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@title = '客户']</value>
      <webElementGuid>96c36867-bc65-4feb-8fba-6e17307b7a8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@title = '客户']</value>
      <webElementGuid>aa90a5c9-fbb0-43e0-b4d9-3bd9535d7540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = '客户' and (text() = '客户' or . = '客户')]</value>
      <webElementGuid>fb58165a-bc1c-4d00-babb-a7d6a0b1c273</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
