<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__r1v</name>
   <tag></tag>
   <elementGuidId>a576a6ea-57a4-4290-8506-ef94532ecabc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-describedby=&quot;\:r1v\:&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-describedby = ':r1v:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;物料归类审核&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>06ccd8fd-8675-4bdd-b661-a2e878b0095d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:r1v:</value>
      <webElementGuid>73d65ca7-e71e-490b-adde-9382479299c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ClassManagement/CommodityClassification</value>
      <webElementGuid>7f8d824f-7898-42fe-a0fa-9fb0e9a7b460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>物料归类审核</value>
      <webElementGuid>79267489-2801-4640-82ad-2f48ae6befc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-992f712319af1e14b67345c6f8c9b387</value>
      <webElementGuid>b19513da-947b-424a-b94c-d1f203d1530c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-describedby = ':r1v:']</value>
      <webElementGuid>16c14d80-c885-4e57-8399-1943e4c9f22b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-describedby = ':r1v:']</value>
      <webElementGuid>f8a514d3-e898-4d8f-b324-3e5756c435d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ClassManagement/CommodityClassification' and (text() = '物料归类审核' or . = '物料归类审核')]</value>
      <webElementGuid>e015a13b-4676-436c-ba9a-b6f288892bdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
