<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_rc_select_27</name>
   <tag></tag>
   <elementGuidId>a92e9fe7-02c6-464f-af11-5b935fc8bc9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' required-field ') and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-sm ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-selection-search-input ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.required-field.ant-select-sm .ant-select-selection-search-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#rc_select_27</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e32b60b0-a015-4448-b23f-73e34686c9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>3f32efec-c8e6-4b2e-b6fd-45de28de4958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b44ae94f-9123-43a0-86be-d978211249ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selection-search-input</value>
      <webElementGuid>d81abfd3-0f16-4d7b-bba7-f5458ee5f9b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>4c37fcce-2481-4406-b9fc-aee1b3a3c886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>84bb7afc-35d5-4808-bd5c-f7d6ac3eb365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>c205561d-a06b-4ce3-9ab8-6a62d3895d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>rc_select_27_list</value>
      <webElementGuid>c4f5a943-6e4c-4058-a75d-cb269dcfdeff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>ffe6725e-e786-4fca-bfda-67aaa32b79fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>rc_select_27_list</value>
      <webElementGuid>f438c2bf-4e8c-4215-8bee-8e3eee0a0765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rc_select_27</value>
      <webElementGuid>e8e75b26-e4ca-4ff5-955b-198d25ce59fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>rc_select_27_list_0</value>
      <webElementGuid>a10e5b51-ee05-4684-a372-ae673b1d38e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-6b3fbc6139b7fd308ad75fa47c3de76a</value>
      <webElementGuid>bcd8a1bb-39f6-4ae2-8c64-ff27f78e1ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' required-field ') and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-sm ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-selection-search-input ')]</value>
      <webElementGuid>d53c6120-7c17-444b-9baf-d210e627570f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' required-field ') and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-sm ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-selection-search-input ')]</value>
      <webElementGuid>86d6a149-93ac-41d8-a613-c70f8e3e6d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'rc_select_27']</value>
      <webElementGuid>44ce5b75-2373-4d05-a4a2-2efeeac76b52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
