<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_svg</name>
   <tag></tag>
   <elementGuidId>afe4335e-bbb2-4834-8853-66194edf26ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-icon=&quot;search&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-icon = 'search']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-icon = 'search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;plus 新增&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>1fffab09-3647-4c21-82f4-92bbe4dc4f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>64 64 896 896</value>
      <webElementGuid>80d6cc28-bac0-439c-89b1-2d37190eddc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0399ff3f-688c-44eb-a366-883e21689287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>b9906f87-5083-4ad7-bd2a-6537427ed5d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>a69f914b-5adc-4a2f-8f13-5692595fc196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>a266518a-7a80-495d-ac11-e64fdda9d1cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>b56cfefb-8c4e-4036-8321-d8633e7983ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cb577e07-b930-44fb-9c0f-dc9dc2b880fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e195258892eda751d569025cb22be555</value>
      <webElementGuid>9d13b151-4a3f-462c-b0f0-28b2463edaba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-icon = 'search']</value>
      <webElementGuid>597bff2e-c646-4dcb-8424-7a2d0826a223</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-icon = 'search']</value>
      <webElementGuid>5b2359c5-2d3d-4aea-9783-3398df59c099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-icon = 'plus']</value>
      <webElementGuid>881d9786-efc5-4953-a7a4-5dbd5a3392ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
