<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_rc-tabs-2-tab-price</name>
   <tag></tag>
   <elementGuidId>19b7175b-3b49-430a-94f0-82a7e717cebc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-node-key = 'price']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-tabs-tab-btn ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-node-key=&quot;price&quot;] .ant-tabs-tab-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e8f5d0ff-9f02-4ffe-aec6-d0fd1a534ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>a02470a9-9212-4427-b496-9bcff8fbf2bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e54e8c77-54cd-439d-b559-9fecf393dd4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-tabs-tab-btn</value>
      <webElementGuid>d5fa02fc-0e2e-481d-8929-bcbe76cf7c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d0370a04-cb9d-4698-9171-1797c11a133f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rc-tabs-2-tab-price</value>
      <webElementGuid>97ac2ab4-e208-4ec2-805b-380fd2054989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>rc-tabs-2-panel-price</value>
      <webElementGuid>c77d2ab3-6f99-4c5b-8f1c-3c929f1c6f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>定价信息</value>
      <webElementGuid>7acd8b63-57f9-4548-8ec2-760d5bcad4ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9331d3aa5580f727f0478d9af81dc09e</value>
      <webElementGuid>06d0cbc2-f42b-4bd9-9e9d-aa8e2fac91e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-node-key = 'price']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-tabs-tab-btn ')]</value>
      <webElementGuid>d8ff38a4-724a-4189-b0d4-7272e2d0bc0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-node-key = 'price']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-tabs-tab-btn ')]</value>
      <webElementGuid>4a5ab2c0-94fa-4d1e-bbf7-659560445cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'rc-tabs-2-tab-price' and (text() = '定价信息' or . = '定价信息')]</value>
      <webElementGuid>93241a73-e13b-4978-9bc4-5c2aa500a94a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
