<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_(007)</name>
   <tag></tag>
   <elementGuidId>6a8c3629-eff2-47b6-abc2-fe96496eab3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(@data = '[object Object]') and (position() = 7)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-item-option-content ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data=&quot;\[object\ Object\]&quot;]:nth-child(7) .ant-select-item-option-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5148579c-c7aa-42ec-b970-1ab1e019d950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item-option-content</value>
      <webElementGuid>69a880cb-fd8f-4db2-a773-71c353f721b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(007)个</value>
      <webElementGuid>d8fe0730-9a1d-47e4-803f-a6596f188afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9824cae711cc62a5e74ee7cb717029f7</value>
      <webElementGuid>245ec59f-7ed4-4f8f-a277-aab76c08e59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@data = '[object Object]') and (position() = 7)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-item-option-content ')]</value>
      <webElementGuid>0aed6c60-a191-460b-abba-80fe86bba462</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@data = '[object Object]') and (position() = 7)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-item-option-content ')]</value>
      <webElementGuid>5b236c60-0f42-4d17-9d1e-50a449c4ae5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '(007)个' or . = '(007)个')]</value>
      <webElementGuid>852ef3dc-765e-4299-a4bd-297822e0b752</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
