<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_rc-tabs-6-tab-businessUnit</name>
   <tag></tag>
   <elementGuidId>e3c79b57-1313-4ef5-a212-78ac4d80850b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-node-key = 'businessUnit']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-tabs-tab-btn ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-node-key=&quot;businessUnit&quot;] .ant-tabs-tab-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a1173305-f8da-4f70-93ee-ffaf8ff6830f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>e5d90abe-ac67-477b-a330-26c39649640a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>35b68bc2-cc40-4ed1-a45c-ae659f51b2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-tabs-tab-btn</value>
      <webElementGuid>f4fda647-9652-49a9-8fdb-57b158ef0952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a3cdc3c0-2107-4d88-9340-ef3b7ef8d14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rc-tabs-6-tab-businessUnit</value>
      <webElementGuid>0a647d39-87e9-46d2-a5da-a7378afb1288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>rc-tabs-6-panel-businessUnit</value>
      <webElementGuid>dd86cff6-891c-4815-94db-3ad5c0040639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>事业部</value>
      <webElementGuid>cb5a7388-a3de-4ec5-9073-688ffca0043a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0f284ead80771960d9f07c615614449a</value>
      <webElementGuid>8c48cca1-4c71-407a-92b5-a8d2d42e13ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-node-key = 'businessUnit']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-tabs-tab-btn ')]</value>
      <webElementGuid>b331437d-cd3f-4e7d-bfbe-f9d43017031e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-node-key = 'businessUnit']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-tabs-tab-btn ')]</value>
      <webElementGuid>512a06a6-ac0b-43a7-a076-1d4cfac5bb9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'rc-tabs-6-tab-businessUnit' and (text() = '事业部' or . = '事业部')]</value>
      <webElementGuid>c9f76773-3ca2-4749-afce-c98f183b940a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
