<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_files</name>
   <tag></tag>
   <elementGuidId>38b14bea-27ec-44ae-9329-716a4481e22a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'files']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;files&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5549a51-9581-4628-a9fc-fea79de82a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>files</value>
      <webElementGuid>a6260dd4-4cd2-4f1c-a316-17c61d3978d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>03a90340-0d9b-4e9f-ad28-1dfae630675b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-63d0d3adfe416997ee526ea8a80c118a</value>
      <webElementGuid>1991d11e-22b9-4adb-a60b-b8ad2ee1f5b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'files']</value>
      <webElementGuid>a0bd4531-ab1b-48de-8aca-036fa6dbceb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'files']</value>
      <webElementGuid>29602a69-1761-4731-a486-a8cc0e417edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'files' and @type = 'file']</value>
      <webElementGuid>8f4b1423-cf6f-4f23-bf90-402fc86f4e40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
