<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KG</name>
   <tag></tag>
   <elementGuidId>3bb43685-cc0f-4752-a18d-b83e667bff32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(@id = 'unitWeight') and @class and contains(concat(' ', normalize-space(@class), ' '), ' ant-input-number-input ') and (@role = 'spinbutton')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#unitWeight.ant-input-number-input[role=&quot;spinbutton&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e306afb-0ae0-4e60-848d-8a1f8736824a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>557131af-e37c-47de-af53-a77832d497e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>1791f762-60d2-45db-a820-8dcf2dcfcd55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0ebe369a-16af-42d9-93c7-5ba7f8aef4ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>aee0bd42-2660-467f-8bda-743e3a618846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unitWeight</value>
      <webElementGuid>07288327-cc92-4fdc-8671-e38fca5f0fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9b80ee66-5cab-47a0-8371-174f35488a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input-number-input</value>
      <webElementGuid>051b86a5-91bc-4008-a473-fb9a1cb86309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-56cb78b6200d8df814b08aacee1f67c3</value>
      <webElementGuid>973b41c5-1100-402d-becd-313c18c23598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@id = 'unitWeight') and @class and contains(concat(' ', normalize-space(@class), ' '), ' ant-input-number-input ') and (@role = 'spinbutton')]</value>
      <webElementGuid>3e68336d-e3a2-48ce-a42d-10ec04e32b27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@id = 'unitWeight') and @class and contains(concat(' ', normalize-space(@class), ' '), ' ant-input-number-input ') and (@role = 'spinbutton')]</value>
      <webElementGuid>450044a4-9973-4f54-bbea-1f583982ebbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'unitWeight']</value>
      <webElementGuid>7d14d394-82e0-42d8-bcb0-d2962587b954</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
