<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_rc-tabs-2-tab-price</name>
   <tag></tag>
   <elementGuidId>6004ade4-7582-48bd-bcd4-95644c831d4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-node-key = 'price']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-tabs-tab-btn ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-node-key=&quot;price&quot;] .ant-tabs-tab-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>04e9d2fe-090f-4349-bc4f-44a99b27e72c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>f50afc7e-c1b4-42eb-9f60-c4ca1d3f840c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>30d3b0c9-fcd2-4ebf-b099-794b4a82cfa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-tabs-tab-btn</value>
      <webElementGuid>36cb9d0e-83da-4550-b6f7-53587faa130f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4d08943b-3802-4d68-a0a7-bc09073db1e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rc-tabs-2-tab-price</value>
      <webElementGuid>bf909a63-1e0c-448f-8fd4-0afdbe339f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>rc-tabs-2-panel-price</value>
      <webElementGuid>a158525b-e1d9-4c76-8fe0-5e48b8f75eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>定价信息</value>
      <webElementGuid>93c5d367-2890-4ee5-ac75-cb872231491c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9331d3aa5580f727f0478d9af81dc09e</value>
      <webElementGuid>9e8b9803-804f-4fdc-ae1c-9561d9d9ad24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-node-key = 'price']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-tabs-tab-btn ')]</value>
      <webElementGuid>eb267206-f3a5-4385-9a64-cb585fbb2977</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-node-key = 'price']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-tabs-tab-btn ')]</value>
      <webElementGuid>a289d1ce-9e21-4833-9f68-53b493da1124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'rc-tabs-2-tab-price' and (text() = '定价信息' or . = '定价信息')]</value>
      <webElementGuid>ff037124-a0e7-4047-9bee-89736ebca7f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
