<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__3</name>
   <tag></tag>
   <elementGuidId>0960c99e-76c7-42f6-bbf4-9c578d99e08e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'itemName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#itemName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e39e863-c52d-4d76-990e-8db77072be3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>请输入</value>
      <webElementGuid>dded5c5f-7477-4925-82d0-fadb3f735550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itemName</value>
      <webElementGuid>8b9d225a-b755-4685-a648-9b8018c95dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>10914bfa-9b9c-43c2-b76e-6f54c29155ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-sm css-oiqwb9 ant-input-outlined</value>
      <webElementGuid>45a5b8c0-4969-439c-ae26-d66f73a3d8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae18fb22-536d-4be2-bf25-1db47d22dc53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e616e1a6f8d11798baffd4c5a0719249</value>
      <webElementGuid>0e360a01-500e-4108-b785-5e55f7b421d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'itemName']</value>
      <webElementGuid>b83a9eb7-abda-4d25-a044-5cb3efee09d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'itemName']</value>
      <webElementGuid>a7dd9e1c-29a2-4e4a-9c1c-58927feb5c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '请输入' and @id = 'itemName' and @type = 'text']</value>
      <webElementGuid>a314b67b-3304-4dda-809e-26b4ed0f3dbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
