<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__1</name>
   <tag></tag>
   <elementGuidId>21afebf7-1c66-46b3-9c75-9c9e5d2f8702</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'unitCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#unitCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00c9c294-2d6b-45d6-a30c-2ce3aef1b1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>请输入</value>
      <webElementGuid>dcd6feb8-bd53-43fb-b0e5-ab2b33de04e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unitCode</value>
      <webElementGuid>a7f5c3d2-bac1-473a-9b19-6157b23008d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f5721986-d284-4b90-903e-30cf7ea7a18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-sm css-oiqwb9 ant-input-outlined</value>
      <webElementGuid>e83e51aa-5705-4b6f-8705-3fe0084d6200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ceac8800-b7b3-4efb-bbcd-9c6e376738a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0943827aa2d9f3f622c19864cdca6e55</value>
      <webElementGuid>d7359c02-c15d-4c27-9d19-767ae4a1ee06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'unitCode']</value>
      <webElementGuid>b889fa5d-5e4d-446c-8857-663e0eae8199</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'unitCode']</value>
      <webElementGuid>28b33dd4-0df7-41ea-a22f-da553e74e294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '请输入' and @id = 'unitCode' and @type = 'text']</value>
      <webElementGuid>a24bc13a-1769-46c7-8f47-811945b05f21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
