<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_rc_select_34</name>
   <tag></tag>
   <elementGuidId>7a3d0784-9851-48e0-98b5-c0ec15075a1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.required-field.ant-select-sm .ant-select-selection-search-input[aria-autocomplete=&quot;list&quot;][role=&quot;combobox&quot;][type=&quot;search&quot;][aria-haspopup=&quot;listbox&quot;][autocomplete=&quot;off&quot;][value=&quot;&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' required-field ') and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-sm ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-selection-search-input ') and (@aria-autocomplete = 'list') and (@role = 'combobox') and (@type = 'search') and (@aria-haspopup = 'listbox') and (@autocomplete = 'off') and (@value = '')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86c33d81-ccd3-4e88-874a-a01aa495a6ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>c9444414-736a-4d5a-810b-948e9fa22eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3fe42e5f-5d88-43c9-b249-5b65a12cd8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selection-search-input</value>
      <webElementGuid>b0cb3ffc-77c6-4719-b763-1030ffe74113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>ef819493-f22f-4188-8eaf-12274a344763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2f61ded3-5d95-45ef-949a-d9633cf51689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>2340c3bb-ec71-4700-95c3-2d84f28d5438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>rc_select_34_list</value>
      <webElementGuid>b885ce43-5ba7-4a7c-8b56-9aecfc4980be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>428817d9-eb8e-43a3-90a3-4662480d2a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>rc_select_34_list</value>
      <webElementGuid>e352135d-ac7b-4b3e-97ea-210d89a9f1f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rc_select_34</value>
      <webElementGuid>3eed3649-72d8-45c5-a61a-3ce4dff17b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>rc_select_34_list_0</value>
      <webElementGuid>06334605-7a81-4e24-9ef4-8c35cd8c7e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-66df7ff4847b26407c325cdf0c40ec0d</value>
      <webElementGuid>ef586811-e815-4cf3-a7ba-74ac4c39331d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' required-field ') and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-sm ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-selection-search-input ') and (@aria-autocomplete = 'list') and (@role = 'combobox') and (@type = 'search') and (@aria-haspopup = 'listbox') and (@autocomplete = 'off') and (@value = '')]</value>
      <webElementGuid>99f2202b-14e5-48ee-bfcc-335b62471488</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' required-field ') and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-sm ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ant-select-selection-search-input ') and (@aria-autocomplete = 'list') and (@role = 'combobox') and (@type = 'search') and (@aria-haspopup = 'listbox') and (@autocomplete = 'off') and (@value = '')]</value>
      <webElementGuid>c031e340-cdab-4171-ab3a-09f4a875e699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'rc_select_34']</value>
      <webElementGuid>ebb807f8-f861-4574-a74b-c13ff5605cea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
