<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__6</name>
   <tag></tag>
   <elementGuidId>41f05921-5c77-4e51-8fc8-5acd92f94ce0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ouName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'ouName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce792314-f84f-4b62-8cbe-411da023b6e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>请输入事业部名称</value>
      <webElementGuid>2847d542-0b00-4950-9af9-d6f6e54aadd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ouName</value>
      <webElementGuid>992d6f17-e3b4-49e8-afdb-3ab1fd1815ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-sm css-oiqwb9</value>
      <webElementGuid>6ae06cf5-7bcd-4de1-a042-430d0ab59c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db8141f6-2111-4ae2-9b31-bb1d0eeab708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d0970c73d54a588ca96244bb5ead623d</value>
      <webElementGuid>20202af4-1c39-4735-960f-6bc7e4216a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'ouName']</value>
      <webElementGuid>7e195b2d-b17c-4226-adc6-6550cbbc102e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'ouName']</value>
      <webElementGuid>3f60fc9f-faef-46b4-97c0-70ad849becb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '请输入事业部名称' and @id = 'ouName' and @type = 'text']</value>
      <webElementGuid>c33468f2-1cd9-449a-9039-084ae4120ac5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
