<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KG</name>
   <tag></tag>
   <elementGuidId>389db65b-8bae-458a-ab35-13fa5fcbb7a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unitWeight.ant-input-number-input[role=&quot;spinbutton&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(@id = 'unitWeight') and @class and contains(concat(' ', normalize-space(@class), ' '), ' ant-input-number-input ') and (@role = 'spinbutton')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27bf5807-0de0-4cde-b126-6f1dedd20d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dca5c762-ba23-4cc1-b632-59038aa39ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>6bf18805-c200-4545-9226-dd6228883881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>70148078-ede4-41a8-99d5-e675372ce5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e2bab1f6-3c2f-487b-8998-11c80814cc75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unitWeight</value>
      <webElementGuid>6c362ecd-3d3c-440e-b1d1-5a3b7459397a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>769af259-c552-48aa-9b16-be152ad43258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input-number-input</value>
      <webElementGuid>f2289062-65b4-4da7-ad39-c3ae9ae275c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-56cb78b6200d8df814b08aacee1f67c3</value>
      <webElementGuid>fd240663-2df0-4c4e-8d77-e41d79264d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@id = 'unitWeight') and @class and contains(concat(' ', normalize-space(@class), ' '), ' ant-input-number-input ') and (@role = 'spinbutton')]</value>
      <webElementGuid>bd33c56a-a147-4f2e-9665-8d6cb180b368</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@id = 'unitWeight') and @class and contains(concat(' ', normalize-space(@class), ' '), ' ant-input-number-input ') and (@role = 'spinbutton')]</value>
      <webElementGuid>62d2a3b7-8dee-4a7c-9257-1bda34e47341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'unitWeight']</value>
      <webElementGuid>2fbdc903-7d1d-4a68-868a-5b15937e0c0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
