<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_</name>
   <tag></tag>
   <elementGuidId>1a7ac88c-c019-464a-9f00-fd53e860b04f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gName[aria-required=&quot;true&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='itemName']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'gName' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b8ec854-73c5-431f-bcd9-5665fec4c86f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gName</value>
      <webElementGuid>941bb4f5-90db-4aa4-b35a-93104826f205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7045ade4-b262-48bc-bf6b-a78c35fe46a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-sm css-oiqwb9 ant-input-outlined</value>
      <webElementGuid>713a8006-2bb5-44df-a44b-5ee132bf9cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1fee34f5-f9ca-4b7a-9cfd-75acb5009f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fdfa2abdbcce7d38ff8cfbb92eb29b43</value>
      <webElementGuid>a9da72f7-ca87-48c5-812c-7666a389b3e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@id = 'gName') and (@aria-required = 'true')]</value>
      <webElementGuid>4003fbca-a91c-45fe-8b13-50bca3970ccc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@id = 'gName') and (@aria-required = 'true')]</value>
      <webElementGuid>79e38840-b8b6-40d5-93ea-450553ba189f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gName' and @type = 'text']</value>
      <webElementGuid>5578f87b-c3ec-4129-8d98-249bf876a261</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
