<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li__r28f</name>
   <tag></tag>
   <elementGuidId>9cc44ef1-22aa-42fb-a09f-a5e229d99873</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-describedby = ':r28f:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-describedby=&quot;\:r28f\:&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>aa109057-219d-4d35-aad0-0a6dad2ef39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-dropdown-menu-item ant-dropdown-menu-item-active min-w-[160px]</value>
      <webElementGuid>f71fde38-7f34-4562-9b0e-242f1fbbdcea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>a65be29e-bdc6-46f3-8fcd-2ac5981ad6b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>095b48f4-46bc-490c-b8b4-bee358ce57da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:r28f:</value>
      <webElementGuid>8beda0f5-3532-4eda-bd4e-217f06a0b106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu-id</name>
      <type>Main</type>
      <value>rc-menu-uuid-60151-3-logout</value>
      <webElementGuid>25d8699d-f1ac-43fd-979b-8cc344dbeea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>退出登录</value>
      <webElementGuid>37e50d28-d08c-46ee-909c-64f4e85ead5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-10fe4a5f2a1088052317184c53c70c7f</value>
      <webElementGuid>eab30d5b-e785-4be2-b13b-9d60b96092a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-describedby = ':r28f:']</value>
      <webElementGuid>0803631a-2469-4d64-aabd-40ba19868432</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-describedby = ':r28f:']</value>
      <webElementGuid>4640de82-294c-4dcd-b3d9-a4a45be9e5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '退出登录' or . = '退出登录')]</value>
      <webElementGuid>1ab1b3c3-911d-40c7-8aea-363034ddd1ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
