<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li__r12</name>
   <tag></tag>
   <elementGuidId>e1f33334-80ba-41c3-a445-3f93f0457ff9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-describedby = ':r12:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-describedby=&quot;\:r12\:&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;物料归类管理&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>04546cda-0025-4b26-ae7c-2a70ebac2d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-menu-overflow-item ant-menu-item ant-menu-item-active ant-menu-item-selected ant-menu-item-only-child</value>
      <webElementGuid>24ada83f-e595-4669-a75f-2f71ebcb8bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>10da3f00-bf26-4904-aa6b-104b4ab6ccdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2e1f46d6-62d8-4cc7-91d5-a7b82b684643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:r12:</value>
      <webElementGuid>ff1d3fb9-b4e1-47a7-bcbe-4d377fccb904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu-id</name>
      <type>Main</type>
      <value>rc-menu-uuid-04767-2-1996460059972784130</value>
      <webElementGuid>ad511e6f-7db7-49da-96af-e75ff0c9f206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>物料归类管理</value>
      <webElementGuid>cc98776e-3814-4a5c-a8e1-0c30388912d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-20c0786ece7fe95259d452b3d700efc5</value>
      <webElementGuid>afed8e98-68c7-4cc6-814d-cf3598ea413b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-describedby = ':r12:']</value>
      <webElementGuid>8ce0eab9-64d0-4b6c-997f-712103ca7530</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-describedby = ':r12:']</value>
      <webElementGuid>4f8ec44d-abb4-4a0b-a944-3a08d6a3ab37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '物料归类管理' or . = '物料归类管理')]</value>
      <webElementGuid>d88fb0ba-7828-460e-bdb9-228bf9fdb24d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
