<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_currCode_list</name>
   <tag></tag>
   <elementGuidId>f8a0a2f6-fb82-46e4-bd8a-d2865e77263e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#currCode_list</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'currCode_list']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#currCode_list</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d84b0180-c85b-4948-9ba5-bf47e0f3aaf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>6172724c-ea16-41a8-92cd-7dfe79de6d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>currCode_list</value>
      <webElementGuid>3e4bd9d4-0bc6-4a2c-bc42-a82dad330bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item-empty</value>
      <webElementGuid>cad52033-d2f1-4582-a7d4-a2c57277a2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>暂无数据</value>
      <webElementGuid>df85f769-cda2-4fe3-8335-2dd83c44fb6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a54eacc84964ae02bc042934d8865ec4</value>
      <webElementGuid>9541446f-4bb5-4917-9903-b6e6badbc786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'currCode_list']</value>
      <webElementGuid>0046100b-c151-4b73-927f-fb27fc569474</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'currCode_list']</value>
      <webElementGuid>2d608eea-5456-4fcd-b276-f1357859eabb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'currCode_list' and (text() = '暂无数据' or . = '暂无数据')]</value>
      <webElementGuid>732c3338-6cfd-4987-b94d-48b0b8723ae5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
