<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__1</name>
   <tag></tag>
   <elementGuidId>1e3ceaa2-0386-4043-9f0c-9a4312a84a15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#itemName.ant-input-sm.ant-input-outlined[placeholder=&quot;请输入&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(@id = 'itemName') and @class and contains(concat(' ', normalize-space(@class), ' '), ' ant-input-sm ') and contains(concat(' ', normalize-space(@class), ' '), ' ant-input-outlined ') and (@placeholder = '请输入')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;请输入&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>957f5278-0b62-458a-8d53-77ca18ecf8b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>请输入</value>
      <webElementGuid>f8bf8f95-9f3e-4dc1-a9d1-ad26169a314a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itemName</value>
      <webElementGuid>7782739b-c513-490c-a172-66ffe1e9df08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-sm css-oiqwb9 ant-input-outlined</value>
      <webElementGuid>eacca5d8-41ec-4aef-b97d-4cf8b2fb4515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ed8ebd9-0246-4ad8-adcd-1db68b073703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b5b2922e34f9f71d49e87f194677064f</value>
      <webElementGuid>6c49eff6-e7c8-4552-9183-5f5a126b694e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@id = 'itemName') and @class and contains(concat(' ', normalize-space(@class), ' '), ' ant-input-sm ') and contains(concat(' ', normalize-space(@class), ' '), ' ant-input-outlined ') and (@placeholder = '请输入')]</value>
      <webElementGuid>73f07116-0034-4412-861d-452303b2748d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@id = 'itemName') and @class and contains(concat(' ', normalize-space(@class), ' '), ' ant-input-sm ') and contains(concat(' ', normalize-space(@class), ' '), ' ant-input-outlined ') and (@placeholder = '请输入')]</value>
      <webElementGuid>592f635d-fa19-4ae7-be8e-c05d52fdc095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '请输入' and @id = 'itemName' and @type = 'text']</value>
      <webElementGuid>74cb072a-c339-4a57-85c1-6ff2016cb380</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
